version: '3'

services:
  app:
    image: 'javaworkshop:latest'
    build:
      context: .
    container_name: application
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/world-db
      - SPRING_DATASOURCE_USERNAME=world
      - SPRING_DATASOURCE_PASSWORD=world123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
  db:
    image: 'ghusta/postgres-world-db:2.5'
